2025-06-06 15:52:18,185 INFO    MainThread:162554 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-06-06 15:52:18,185 INFO    MainThread:162554 [wandb_setup.py:_flush():67] Configure stats pid to 162554
2025-06-06 15:52:18,185 INFO    MainThread:162554 [wandb_setup.py:_flush():67] Loading settings from /home/namhoai/.config/wandb/settings
2025-06-06 15:52:18,185 INFO    MainThread:162554 [wandb_setup.py:_flush():67] Loading settings from /home/namhoai/WorkSpace/WriteViT/wandb/settings
2025-06-06 15:52:18,185 INFO    MainThread:162554 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-06-06 15:52:18,185 INFO    MainThread:162554 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/namhoai/WorkSpace/WriteViT/wandb/run-20250606_155218-wsu2pihz/logs/debug.log
2025-06-06 15:52:18,185 INFO    MainThread:162554 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/namhoai/WorkSpace/WriteViT/wandb/run-20250606_155218-wsu2pihz/logs/debug-internal.log
2025-06-06 15:52:18,185 INFO    MainThread:162554 [wandb_init.py:init():761] calling init triggers
2025-06-06 15:52:18,185 INFO    MainThread:162554 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-06-06 15:52:18,185 INFO    MainThread:162554 [wandb_init.py:init():784] starting backend
2025-06-06 15:52:18,185 INFO    MainThread:162554 [wandb_init.py:init():788] sending inform_init request
2025-06-06 15:52:18,188 INFO    MainThread:162554 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-06-06 15:52:18,189 INFO    MainThread:162554 [wandb_init.py:init():798] backend started and connected
2025-06-06 15:52:18,189 INFO    MainThread:162554 [wandb_init.py:init():891] updated telemetry
2025-06-06 15:52:18,192 INFO    MainThread:162554 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-06-06 15:52:18,928 ERROR   MainThread:162554 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/home/namhoai/WorkSpace/env/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
  File "/home/namhoai/WorkSpace/env/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 963, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 401: {"data":{"upsertBucket":null},"errors":[{"message":"user is not logged in","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}]}
2025-06-06 15:52:19,929 INFO    MsgRouterThr:162554 [mailbox.py:close():129] Closing mailbox, abandoning 0 handles.
